import '../models/game.dart';
import '../models/event.dart';
import '../models/participant.dart';

final mockEvent = DiceDaysEvent(
  id: 'evt-1',
  name: 'Dice Days 12',
  code: 'DD12',
  startDate: DateTime(2026, 8, 14),
  endDate: DateTime(2026, 8, 17),
  location: 'Ferienhaus am See',
  createdAt: DateTime(2026, 6, 1),
);

final mockParticipants = [
  Participant(id: 'p-me', eventId: 'evt-1', nickname: 'Denis', joinedAt: DateTime(2026, 6, 1)),
  Participant(id: 'p-2', eventId: 'evt-1', nickname: 'Marco', joinedAt: DateTime(2026, 6, 1)),
  Participant(id: 'p-3', eventId: 'evt-1', nickname: 'Lisa', joinedAt: DateTime(2026, 6, 2)),
  Participant(id: 'p-4', eventId: 'evt-1', nickname: 'Tom', joinedAt: DateTime(2026, 6, 2)),
  Participant(id: 'p-5', eventId: 'evt-1', nickname: 'Anna', joinedAt: DateTime(2026, 6, 3)),
  Participant(id: 'p-6', eventId: 'evt-1', nickname: 'Chris', joinedAt: DateTime(2026, 6, 3)),
];

const _currentUserId = 'p-me';

String get currentUserId => _currentUserId;

final mockGames = [
  Game(
    id: 'g-1',
    eventId: 'evt-1',
    name: 'Wingspan',
    bggId: '266192',
    imageUrl: 'https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__original/img/uIjeoKgHMcRtzRSR4MoUYl3nXxs=/0x0/filters:format(jpeg)/pic4458123.jpg',
    minPlayers: 1,
    maxPlayers: 5,
    playingTimeMinutes: 70,
    weight: 2.44,
    interestedParticipantIds: ['p-me', 'p-2', 'p-3', 'p-4'],
    explainerParticipantIds: ['p-2'],
    supplierParticipantIds: ['p-2'],
    needsExplanationParticipantIds: ['p-me', 'p-3'],
    createdAt: DateTime(2026, 6, 5),
  ),
  Game(
    id: 'g-2',
    eventId: 'evt-1',
    name: 'Brass: Birmingham',
    bggId: '224517',
    imageUrl: 'https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__original/img/-ZMILz-GBnSTz_ZSppHRGLlx_J4=/0x0/filters:format(jpeg)/pic3490053.jpg',
    minPlayers: 2,
    maxPlayers: 4,
    playingTimeMinutes: 120,
    weight: 3.87,
    interestedParticipantIds: ['p-me', 'p-2', 'p-3', 'p-4', 'p-5'],
    explainerParticipantIds: [],
    supplierParticipantIds: ['p-me'],
    needsExplanationParticipantIds: ['p-3', 'p-4', 'p-5'],
    createdAt: DateTime(2026, 6, 5),
  ),
  Game(
    id: 'g-3',
    eventId: 'evt-1',
    name: 'Cascadia',
    bggId: '295947',
    imageUrl: 'https://cf.geekdo-images.com/MjeJZfulbsM1DSV3DrGJYA__original/img/B374C04Eip7fAZAJufxkgMiTpoQ=/0x0/filters:format(jpeg)/pic5100691.jpg',
    minPlayers: 1,
    maxPlayers: 4,
    playingTimeMinutes: 45,
    weight: 1.85,
    interestedParticipantIds: ['p-me', 'p-3'],
    explainerParticipantIds: ['p-me'],
    supplierParticipantIds: ['p-me'],
    createdAt: DateTime(2026, 6, 6),
  ),
  Game(
    id: 'g-4',
    eventId: 'evt-1',
    name: 'Terraforming Mars',
    bggId: '167791',
    imageUrl: 'https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__original/img/thIqWDnH9utKuYlp6BPC9ZaVPGs=/0x0/filters:format(jpeg)/pic3536616.jpg',
    minPlayers: 1,
    maxPlayers: 5,
    playingTimeMinutes: 120,
    weight: 3.24,
    interestedParticipantIds: ['p-2', 'p-4', 'p-5', 'p-6'],
    explainerParticipantIds: ['p-4'],
    supplierParticipantIds: [],
    needsExplanationParticipantIds: ['p-5', 'p-6'],
    createdAt: DateTime(2026, 6, 6),
  ),
  Game(
    id: 'g-5',
    eventId: 'evt-1',
    name: 'Azul',
    bggId: '230802',
    imageUrl: 'https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__original/img/AWofHkFY2GzmLSjpBiEadOt_pJg=/0x0/filters:format(jpeg)/pic6973671.jpg',
    minPlayers: 2,
    maxPlayers: 4,
    playingTimeMinutes: 45,
    weight: 1.77,
    interestedParticipantIds: [],
    explainerParticipantIds: [],
    supplierParticipantIds: [],
    createdAt: DateTime(2026, 6, 7),
  ),
  Game(
    id: 'g-6',
    eventId: 'evt-1',
    name: 'Spirit Island',
    bggId: '162886',
    imageUrl: 'https://cf.geekdo-images.com/kjCm4ZvPjIZxS-mYgSPMsA__original/img/5JMHCKy07RgmsArOyd3Unplj5tg=/0x0/filters:format(jpeg)/pic7013651.jpg',
    minPlayers: 1,
    maxPlayers: 4,
    playingTimeMinutes: 120,
    weight: 3.94,
    interestedParticipantIds: [],
    explainerParticipantIds: [],
    supplierParticipantIds: [],
    createdAt: DateTime(2026, 6, 7),
  ),
];
